language: python
python:
  - '2.7'
  - '3.7'
before_install:
  - pip install tox
  - pip install coverage
  - pip install python-coveralls
  - pip install codacy-coverage
install:
  - pip install -r requirements.txt
  - pip install .
addons:
  sonarcloud:
    organization: "unofficial-memsource"
    token:
      secure: "kWD+agvgUE3soi1PkBVB671U0NFOezP8AmqQwecvsQmKIjSrNliRBreewi4jZhAA0zz8nScji8kkZiA25QW3BC0irndmhXbhav49VK6nXb4ZVnz5l74C3PI9ICttLajWdjAwkhgmIJwkMgg6PjF/Y+u0NLCMOrgsdasZHflD+xhwFkya5tQSJsMGgkrpoGJa1sqeoLbfZmwQvrMlimntR4hOVad5B5BEchqkpx6YuDJRLgCvTgfRTkrAKuwvrXHO02p6F1wYZjqm/HhgIOAhIXxBg64VcJnUxnNNZt6z5sb8RzqF0Bs3Ct/0+wpRw2pbDbLpEJDjCuszseigl9rQ3uBKULpYzq9U+UM2K1+FsjUJMxy6VHybpzHzUKSpZvrAuhOTnR6IgaWbKubrUeGlGtA0kPrx1PxA7pSYAK5Osm6up7CqrdSrRc7tgQq3DkBDhMLkpH+0ol8RtzsJp3kYKgKCBar6tAtENXfvRkwA0gIJM42wbJuf74kbxlMO9/2dljEeLbl3Cvu9SrLYkqbbNaygZqRTGROth+lkqQ5mE4I+pV5jaMVbSUAECpyXu5/27+kkBGW7WvwlAbesWlNUhjVAbVdTFIz0gsA19O+Z7uaBRFlNaCNq4bQkHrg1V3cZ/ceQEE6YN+tW4FGdua4HoQDwmw2J1d+P2EZczFeG0vI="
script:
  - tox
  - sonar-scanner
  - coverage xml
  - python-codacy-coverage -r coverage.xml
  - memsource --help
deploy:
  - provider: pypi
    distributions: sdist
    user: __token__
    password:
      secure: PRMgu72DU6LFSvqn82YrJbrlzF8X+WTo8y6BuReOQEBQsr9UKYdDDsC2fp9XudG7g/B3RdavO1B8NGHYJuck2khB2sUSed06hk5G/TdvVSEilHplkiq5NHKfF5HeYcftcy7zBqJYjwO0tAdtP8qDS7RFbJWuIFvwJnpRQS+bEH3QGJr8Zh09JsS6m2srRu8O+WnB+V8wh+Zbsw3jTYCO3/DOHtKbooKalLGKWqv5VkSnHvShmzd+OMr0G7KzEDIjFCWgZrGuw8w7CIS9QnfcnnWUg5/XEuyRi2GF1LdLVWY//vtpeeRMSuJIXJ0RyGeCyhf+1SOWhrHSzY9g32ypxBQ67xWBIb3i8D3nL93fQ08GD1ZFySvEqvmuFRuUbZLMnkkPMiYNJBXJNfP9Z83bsCC/nazhDvwyQ/zMdWySN+KXjMlu6tn11MT6I3/zigVqsqsUfh+S9rA3pt6jtaDc9ENjz9Vs5C2os1poSGtdzrIj4CMWf7UH2AbVE+yaaaP3CKKmpkryfDNMKk6pnzxqrPRddv0nja3w62oxjECQaQVk0Vj2xQxha4NIrzCTD7NOXsIGxe/27DiBtx4S5XS4IZpmEEtDi4BTUXkhOMuq6lcAPVYWUa4XIq0AGGqVRjSF9K+ZUUNMtiJlWW4U7mKVS0zxHr2V8py6AHn1+d5td9U=
    on:
      tags: true
    skip_existing: true
  - provider: releases
    user: nemakacenko
    api_key:
      secure: "c4tGqVdw0p9MB4RyDjXdJ/Q1xNAijqkZOUSuq+cBXyCmKNBZAXaDXheW7elaXJK37GS1ID7N3Q1lCbzHF2gIe3o2LxYpbRHG4BgBYl/ZCna7wwA35jVpApwe11L5bcX4oufpu4KRM1oP4RnEtuFQCMoOEVwBNzkWcGkfyIIo1tZAusEKwX7lCFI896LHZJKTJhEY7f3hcS9sUV0OVWzdtUim7sWnoLR0niN6yyGbfekZW89vBrLrKs0usqJfaHgeAJUtkmU2aC1PuYygAMdRhDtfxUg3UjSE5oZcjfGk1e8FIwMlv+txxuIg/qDXxFJYCdQbXGj1NNUnZ/lFg/UR07zoqXrzACX1HpqDnnGBHwmA8V8NDaBrrnCE7Dk0NoEZ56xm3zbgbfnctx655cpGXaOsVAnxz/0jqPYEuCraM10pUlRAERIKbM9gTjJK/hp0J8yW3iN5sLmqQXUh/DwbRxU7Ew8bcdRp5Dsp9qRJ72IjstzKq8tAO5/r2KyZZ6tD8pN9M7oOfNIg2GoSQk9prZdudm1FkL7ag2UxVAu7mub/RHIhR95aL/XZvOkVM6ZN1oONMk7OY8gL87XfZCsv52U54VDyHV3XahXlcqHQfMaJbL3tQo19dxhywgnSRVBjNWNq2raYd6R1O4JbwhBBg3UqdIWvX0BSDs8D1FEAbDY="
    skip_cleanup: true
    on:
      tags: true
after_success:
- coveralls
